[2024-07-05T12:49:18.343+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_scraping_75.run_dbt manual__2024-07-05T11:43:31.990172+00:00 [queued]>
[2024-07-05T12:49:18.350+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_scraping_75.run_dbt manual__2024-07-05T11:43:31.990172+00:00 [queued]>
[2024-07-05T12:49:18.350+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-05T12:49:18.361+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): run_dbt> on 2024-07-05 11:43:31.990172+00:00
[2024-07-05T12:49:18.366+0000] {standard_task_runner.py:60} INFO - Started process 47707 to run task
[2024-07-05T12:49:18.368+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_scraping_75', 'run_dbt', 'manual__2024-07-05T11:43:31.990172+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/daily_scraping_dag_75.py', '--cfg-path', '/tmp/tmpxec8tw0e']
[2024-07-05T12:49:18.370+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask run_dbt
[2024-07-05T12:49:18.382+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-05T12:49:18.408+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_scraping_75.run_dbt manual__2024-07-05T11:43:31.990172+00:00 [running]> on host 596f6ace9042
[2024-07-05T12:49:18.459+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_scraping_75' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T11:43:31.990172+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T11:43:31.990172+00:00'
[2024-07-05T12:49:18.461+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-05T12:49:18.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/scraping_dbt && dbt run --profiles-dir /opt/***/dbt_profiles']
[2024-07-05T12:49:18.470+0000] {subprocess.py:86} INFO - Output:
[2024-07-05T12:49:19.997+0000] {subprocess.py:93} INFO - [0m12:49:19  Running with dbt=1.8.3
[2024-07-05T12:49:20.241+0000] {subprocess.py:93} INFO - [0m12:49:20  Registered adapter: postgres=1.8.2
[2024-07-05T12:49:20.775+0000] {subprocess.py:93} INFO - [0m12:49:20  Found 7 models, 1 snapshot, 4 data tests, 1 seed, 2 sources, 531 macros
[2024-07-05T12:49:20.777+0000] {subprocess.py:93} INFO - [0m12:49:20
[2024-07-05T12:49:20.906+0000] {subprocess.py:93} INFO - [0m12:49:20  Concurrency: 1 threads (target='dev')
[2024-07-05T12:49:20.907+0000] {subprocess.py:93} INFO - [0m12:49:20
[2024-07-05T12:49:20.914+0000] {subprocess.py:93} INFO - [0m12:49:20  1 of 7 START sql table model public.src_ads .................................... [RUN]
[2024-07-05T12:49:21.044+0000] {subprocess.py:93} INFO - [0m12:49:21  1 of 7 OK created sql table model public.src_ads ............................... [[32mSELECT 195[0m in 0.13s]
[2024-07-05T12:49:21.046+0000] {subprocess.py:93} INFO - [0m12:49:21  2 of 7 START sql table model public.src_prix_m2 ................................ [RUN]
[2024-07-05T12:49:21.100+0000] {subprocess.py:93} INFO - [0m12:49:21  2 of 7 OK created sql table model public.src_prix_m2 ........................... [[32mSELECT 246[0m in 0.05s]
[2024-07-05T12:49:21.102+0000] {subprocess.py:93} INFO - [0m12:49:21  3 of 7 START sql table model public.dim_ads_images_url ......................... [RUN]
[2024-07-05T12:49:21.161+0000] {subprocess.py:93} INFO - [0m12:49:21  3 of 7 OK created sql table model public.dim_ads_images_url .................... [[32mSELECT 1950[0m in 0.06s]
[2024-07-05T12:49:21.163+0000] {subprocess.py:93} INFO - [0m12:49:21  4 of 7 START sql table model public.dim_ads_tags ............................... [RUN]
[2024-07-05T12:49:21.225+0000] {subprocess.py:93} INFO - [0m12:49:21  4 of 7 OK created sql table model public.dim_ads_tags .......................... [[32mSELECT 1928[0m in 0.06s]
[2024-07-05T12:49:21.227+0000] {subprocess.py:93} INFO - [0m12:49:21  5 of 7 START sql table model public.src_ads_cleaned ............................ [RUN]
[2024-07-05T12:49:21.254+0000] {subprocess.py:93} INFO - [0m12:49:21  5 of 7 ERROR creating sql table model public.src_ads_cleaned ................... [[31mERROR[0m in 0.03s]
[2024-07-05T12:49:21.256+0000] {subprocess.py:93} INFO - [0m12:49:21  6 of 7 START sql incremental model public.src_ads_cleaned_backup_incremental ... [RUN]
[2024-07-05T12:49:21.399+0000] {subprocess.py:93} INFO - [0m12:49:21  6 of 7 OK created sql incremental model public.src_ads_cleaned_backup_incremental  [[32mINSERT 0 195[0m in 0.14s]
[2024-07-05T12:49:21.401+0000] {subprocess.py:93} INFO - [0m12:49:21  7 of 7 SKIP relation public.dim_ads_details .................................... [[33mSKIP[0m]
[2024-07-05T12:49:21.415+0000] {subprocess.py:93} INFO - [0m12:49:21
[2024-07-05T12:49:21.415+0000] {subprocess.py:93} INFO - [0m12:49:21  Finished running 6 table models, 1 incremental model in 0 hours 0 minutes and 0.64 seconds (0.64s).
[2024-07-05T12:49:21.452+0000] {subprocess.py:93} INFO - [0m12:49:21
[2024-07-05T12:49:21.453+0000] {subprocess.py:93} INFO - [0m12:49:21  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-05T12:49:21.453+0000] {subprocess.py:93} INFO - [0m12:49:21
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO - [0m12:49:21    Database Error in model src_ads_cleaned (models/src/src_ads_cleaned.sql)
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO -   column s.id does not exist
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO -   LINE 34:         s.id = la.id
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO -                    ^
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO -   compiled Code at target/run/scraping_dbt/models/src/src_ads_cleaned.sql
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO - [0m12:49:21
[2024-07-05T12:49:21.454+0000] {subprocess.py:93} INFO - [0m12:49:21  Done. PASS=5 WARN=0 ERROR=1 SKIP=1 TOTAL=7
[2024-07-05T12:49:22.120+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-05T12:49:22.128+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-05T12:49:22.131+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=daily_scraping_75, task_id=run_dbt, execution_date=20240705T114331, start_date=20240705T124918, end_date=20240705T124922
[2024-07-05T12:49:22.142+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 47707)
[2024-07-05T12:49:22.151+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-05T12:49:22.163+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
