[2024-07-05T10:06:45.645+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_scraping.run_dbt manual__2024-07-05T09:59:57.907593+00:00 [queued]>
[2024-07-05T10:06:45.651+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_scraping.run_dbt manual__2024-07-05T09:59:57.907593+00:00 [queued]>
[2024-07-05T10:06:45.651+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-05T10:06:45.660+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): run_dbt> on 2024-07-05 09:59:57.907593+00:00
[2024-07-05T10:06:45.664+0000] {standard_task_runner.py:60} INFO - Started process 31259 to run task
[2024-07-05T10:06:45.666+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_scraping', 'run_dbt', 'manual__2024-07-05T09:59:57.907593+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/daily_scraping_dag.py', '--cfg-path', '/tmp/tmptmerhj3d']
[2024-07-05T10:06:45.668+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask run_dbt
[2024-07-05T10:06:45.678+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-05T10:06:45.703+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_scraping.run_dbt manual__2024-07-05T09:59:57.907593+00:00 [running]> on host 596f6ace9042
[2024-07-05T10:06:45.775+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_scraping' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T09:59:57.907593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T09:59:57.907593+00:00'
[2024-07-05T10:06:45.776+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-05T10:06:45.777+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/scraping_dbt && dbt run --profiles-dir /opt/***/dbt_profiles']
[2024-07-05T10:06:45.786+0000] {subprocess.py:86} INFO - Output:
[2024-07-05T10:06:47.210+0000] {subprocess.py:93} INFO - [0m10:06:47  Running with dbt=1.8.3
[2024-07-05T10:06:47.440+0000] {subprocess.py:93} INFO - [0m10:06:47  Registered adapter: postgres=1.8.2
[2024-07-05T10:06:47.950+0000] {subprocess.py:93} INFO - [0m10:06:47  Found 7 models, 1 snapshot, 4 data tests, 1 seed, 2 sources, 531 macros
[2024-07-05T10:06:47.952+0000] {subprocess.py:93} INFO - [0m10:06:47
[2024-07-05T10:06:48.072+0000] {subprocess.py:93} INFO - [0m10:06:48  Concurrency: 1 threads (target='dev')
[2024-07-05T10:06:48.072+0000] {subprocess.py:93} INFO - [0m10:06:48
[2024-07-05T10:06:48.080+0000] {subprocess.py:93} INFO - [0m10:06:48  1 of 7 START sql table model public.src_ads .................................... [RUN]
[2024-07-05T10:06:48.197+0000] {subprocess.py:93} INFO - [0m10:06:48  1 of 7 OK created sql table model public.src_ads ............................... [[32mSELECT 195[0m in 0.12s]
[2024-07-05T10:06:48.199+0000] {subprocess.py:93} INFO - [0m10:06:48  2 of 7 START sql table model public.src_prix_m2 ................................ [RUN]
[2024-07-05T10:06:48.246+0000] {subprocess.py:93} INFO - [0m10:06:48  2 of 7 OK created sql table model public.src_prix_m2 ........................... [[32mSELECT 246[0m in 0.05s]
[2024-07-05T10:06:48.248+0000] {subprocess.py:93} INFO - [0m10:06:48  3 of 7 START sql table model public.dim_ads_images_url ......................... [RUN]
[2024-07-05T10:06:48.298+0000] {subprocess.py:93} INFO - [0m10:06:48  3 of 7 OK created sql table model public.dim_ads_images_url .................... [[32mSELECT 1950[0m in 0.05s]
[2024-07-05T10:06:48.300+0000] {subprocess.py:93} INFO - [0m10:06:48  4 of 7 START sql table model public.dim_ads_tags ............................... [RUN]
[2024-07-05T10:06:48.354+0000] {subprocess.py:93} INFO - [0m10:06:48  4 of 7 OK created sql table model public.dim_ads_tags .......................... [[32mSELECT 1928[0m in 0.05s]
[2024-07-05T10:06:48.355+0000] {subprocess.py:93} INFO - [0m10:06:48  5 of 7 START sql table model public.src_ads_cleaned ............................ [RUN]
[2024-07-05T10:06:48.381+0000] {subprocess.py:93} INFO - [0m10:06:48  5 of 7 ERROR creating sql table model public.src_ads_cleaned ................... [[31mERROR[0m in 0.02s]
[2024-07-05T10:06:48.383+0000] {subprocess.py:93} INFO - [0m10:06:48  6 of 7 START sql incremental model public.src_ads_cleaned_backup_incremental ... [RUN]
[2024-07-05T10:06:48.516+0000] {subprocess.py:93} INFO - [0m10:06:48  6 of 7 OK created sql incremental model public.src_ads_cleaned_backup_incremental  [[32mINSERT 0 195[0m in 0.13s]
[2024-07-05T10:06:48.518+0000] {subprocess.py:93} INFO - [0m10:06:48  7 of 7 SKIP relation public.dim_ads_details .................................... [[33mSKIP[0m]
[2024-07-05T10:06:48.531+0000] {subprocess.py:93} INFO - [0m10:06:48
[2024-07-05T10:06:48.531+0000] {subprocess.py:93} INFO - [0m10:06:48  Finished running 6 table models, 1 incremental model in 0 hours 0 minutes and 0.58 seconds (0.58s).
[2024-07-05T10:06:48.570+0000] {subprocess.py:93} INFO - [0m10:06:48
[2024-07-05T10:06:48.571+0000] {subprocess.py:93} INFO - [0m10:06:48  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-05T10:06:48.571+0000] {subprocess.py:93} INFO - [0m10:06:48
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO - [0m10:06:48    Database Error in model src_ads_cleaned (models/src/src_ads_cleaned.sql)
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO -   column s.id does not exist
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO -   LINE 34:         s.id = la.id
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO -                    ^
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO -   compiled Code at target/run/scraping_dbt/models/src/src_ads_cleaned.sql
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO - [0m10:06:48
[2024-07-05T10:06:48.572+0000] {subprocess.py:93} INFO - [0m10:06:48  Done. PASS=5 WARN=0 ERROR=1 SKIP=1 TOTAL=7
[2024-07-05T10:06:49.214+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-05T10:06:49.222+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-05T10:06:49.225+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=daily_scraping, task_id=run_dbt, execution_date=20240705T095957, start_date=20240705T100645, end_date=20240705T100649
[2024-07-05T10:06:49.234+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 31259)
[2024-07-05T10:06:49.246+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-05T10:06:49.258+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
